name: notebook
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.8*
  - pangeo-notebook=2020.12.22
  - jupyterlab=2.2.9
  - pip=20
  - nb_conda_kernels
  - jupyter-server-proxy
  - jupyter_client
  - lz4=3.1.1
  - s3fs>0.5
  - gcsfs
  - fsspec
  - numpy
  - pandas
  - xarray
  - zarr
  - hdf5
  - pyarrow
  - h5py
  - h5netcdf
  - sphinx-autobuild
  - nbsphinx
  - r-base=4.0.3
  - r-essentials
  - r-tidyverse
  - r-bookdown
  - hail
  - plink
  - plink2
  - scikit-learn
  - pip:
    - pheweb
    - jupyter-rsession-proxy
    - jupyter-book
    - jupyter-cache[cli]
