name: scanpy
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8*
  - pangeo-notebook=2020.11.06
  - pip
  - fsspec
  - gcsfs
  - h5netcdf
  - h5py
  - jupyterlab-nvdashboard
  - matplotlib-base
  - nb_conda_kernels
  - numpy
  - pandas
  - s3fs>0.5
  - scikit-learn
  - scipy
  - zarr
  - scanpy=1.6.0
  - anndata
  - cellxgene
  - pip:
      - nbsphinx
      - jupyter-book
      - jupyter-rsession-proxy
