name: notebook
channels:
  - conda-forge
dependencies:
  - python=3.8*
  - pangeo-notebook=2020.11.06
  - jupyterlab=2.2.9
  - pip=20
  - jupyter-server-proxy
  - jupyter_client
  - lz4=3.1.1
  - s3fs>0.5
  - gcsfs
  - fsspec
  - numpy
  - pandas
  - xarray
  - zarr
  - hdf5
  - pyarrow
  - h5py
  - h5netcdf
  - pip:
      - jupyter-kite
      - jupyter-rsession-proxy
      - jupyter-book
      - nbsphinx
