version: '3'

networks:
  app-tier:
    driver: bridge

services:

  jupyter:
    image: dabbleofdevops/genomics-notebook
    volumes:
      - ./docs:/home/jovyan/docs:z
      - ./:/home/jovyan/app:z
    ports:
      - "8889:8889"
    working_dir: "/home/jovyan"
    networks:
      - app-tier
    command: |
      bash -c "jupyter lab --ip 0.0.0.0 --port 8889 --allow-root"

  # jupyter-book:
  #   build:
  #     context: docs
  #   volumes:
  #     - ./docs:/docs:z
  #     - ./:/app:z
  #   ports:
  #     - "8002:8001"
  #   networks:
  #     - app-tier
  #   command: |
  #     bash -c "source activate notebook && python /docs/run-jupyterbook.py"
