name: cellprofiler
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8*
  - pangeo-notebook=2020.11.06
  - mysql
  - openjdk
  - zeromq
  - pyzmq
  - pip
  - datashader
  - fsspec
  - gcsfs
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - lz4
  - matplotlib-base
  - nb_conda_kernels
  - numpy
  - pandas
  - panel
  - rasterio
  - s3fs>0.5
  - scikit-image
  - scikit-learn
  - scipy
  - sparse
  - xarray
  - zarr
  - wxpython
  - pip:
      - CellProfiler==4.0.7
      - nbsphinx
      - jupyter-book
      - jupyter-rsession-proxy
