name: cellprofiler
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8*
  - pangeo-notebook=2020.12.16
  # NOTE: many of the extensions don't support 3.0 yet
  - jupyterlab=2.2.9
  - mysql
  - openjdk
  - zeromq
  - pyzmq
  - datashader
  - fsspec
  - gcsfs
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - lz4
  - matplotlib-base
  - nb_conda_kernels
  - numpy
  - pandas
  - panel
  - rasterio
  - s3fs>0.5
  - scikit-image
  - scikit-learn
  - scipy
  - sparse
  - xarray
  - zarr
  - wxpython
  # NOTE: pip required for running tests in this repo
  - pip=20
  - pip:
      - CellProfiler==4.0.7
