name: notebook
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pangeo-notebook=2020.12.16
  # NOTE: many of the extensions don't support 3.0 yet
  - jupyterlab=2.2.9
  # NOTE: pip required for running tests in this repo
  - pip=20
  # Python things
  - time
  - gensim
  - bs4
  - selenium
  - sentence-transformers
  - transformers
  - pytorch>=1.6
  - cudatoolkit=10.2
  - wand
  - streamlit
  - nltk
  - spacy
  - scikit-learn
  - requests
  - pkgs/main/linux-64::tensorflow-gpu>=2
  - keras
  # R Things
  - r-base=4.0.3
  - r-base=4.0.3
  - r-essentials
  - r-tidyverse
  - r-plumber
  - r-data.table
  - r-mlr
  - r-glmnet
  - r-rocr
  - r-caret
  - r-mlrmbo
  - h2o-py
  - r-dicekriging
  - r-randomforestsrc
  - r-checkmate
  - r-fastdummies
  - r-jsonlite
  - xgboost
  - r-lubridate
  - r-stringi
  # Pangeo ML
  - adlfs
  - datashader
  - fsspec
  - gcsfs
  - geopandas
  - geoviews-core
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - intake
  - intake-xarray
  - jupyterlab-nvdashboard
  - lz4
  - matplotlib-base
  - nb_conda_kernels
  - numpy
  - pandas
  - panel
  - rasterio
  - s3fs>0.5
  - scikit-image
  - scikit-learn
  - scipy
  - sparse
  - xarray
  - zarr
  - pip:
      - git+git://github.com/titipata/pubmed_parser.git
