name: notebook
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pangeo-notebook=2020.12.16
  # NOTE: many of the extensions don't support 3.0 yet
  - jupyterlab=2.2.9
  # NOTE: pip required for running tests in this repo
  - jupyter-server-proxy
  - jupyter_client
  - pip=20
  - pip:
      - jupyter-kite
      - jupyter-rsession-proxy
