name: notebook
channels:
  - conda-forge
dependencies:
  - python=3.8*
  - pangeo-notebook=2020-12-22
  - jupyterlab=2.2.9
  - pip=20
  - jupyter-server-proxy
  - jupyter_client
  - lz4=3.1.1
  - s3fs>0.5
  - gcfs
  - fsspec
  - numpy
  - pandas
  - xarray
  - zarr
  - hdf5
  - pyarrow
  - h5py
  - h5netcdf
  - r-base=4.0.3
  - r-essentials
  - r-tidyverse
  - r-bookdown
  - pip:
    - jupyter-rsession-proxy
    - jupyter-book
    - nbsphinx
