name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8*
  - pangeo-notebook=2020.11.06
  - pip
  - sphinx
  - sphinx-autobuild=0.7.1
  - numpy
  - pandas
  - pip:
      - nbsphinx
      - jupyter-book
